### ISSUE TITLE
Se muestra SOLO la hora en que se cargó la página, no cuando se le da al botón

### ISSUE THREAD

**Issue by lmagarin** [alvaroolt/alvaroolt.github.io#5]
https://github.com/alvaroolt/alvaroolt.github.io/blob/4c3608fd34d3c9297d78c2ec466a827fc02ecc4e/examen1/parte1/js/ventana.js#L14

**Comment by alvaroolt** [comment]
He cerrado el issue #5 en vez de el #6 por error.
