### ISSUE TITLE
Refactoriza: los dos obtenerHorasActuales y obtenerMinutosActuales hacen lo mismo...

### ISSUE THREAD

**Issue by lmagarin** [alvaroolt/alvaroolt.github.io#6]
https://github.com/alvaroolt/alvaroolt.github.io/blob/4c3608fd34d3c9297d78c2ec466a827fc02ecc4e/examen1/parte1/js/ventana.js#L16

**Comment by alvaroolt** [comment]
La corrección de este issue se encuentra aquí: 080b7a3
